### ISSUE TITLE
opm alpha render-veneer semver should enforce that all bundle references refer to the same package

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-registry#1044]
Given an example schema:
```yaml
Schema: olm.semver
GenerateMajorChannels: true
GenerateMinorChannels: false
Stable:
  Bundles:
  - Image: repository-uri/example-operator:v0.8.9
  - Image: repository-uri/some-other-example-operator:v0.1.0
```

the render-veneer should fail because the listed image refs belong to more than one package.
