### ISSUE TITLE
RFE: opm alpha render-veneer semver should recognize multiple schema in an input veneer

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-registry#1045]
When multiple schema instances are listed in the same doc via the new-doc delimiter (`---`) the render should process each schema independently, in sequence, for e.g.:
```yaml
Schema: olm.semver
GenerateMajorChannels: true
GenerateMinorChannels: false
Stable:
  Bundles:
  - Image: repository-uri/example-operator:v0.8.9
  - Image: repository-uri/example-operator:v0.9.0
---
Schema: olm.semver
GenerateMajorChannels: true
GenerateMinorChannels: false
Stable:
  Bundles:
  - Image: repository-uri/another-example-operator:v0.8.9
  - Image: repository-uri/another-example-operator:v0.9.0
```

Errors would be fatal to processing that independent schema..
