### ISSUE TITLE
'opm alpha render-template semver' fails if ClusterServiceVersion.spec.version is not set

### ISSUE THREAD

**Issue by Jeansen** [operator-framework/operator-registry#1135]
After generating my little test operator, I have the following folder layout:

build/bundle/
└── cert-operator
    ├── bundle.Dockerfile
    ├── manifests
    │   └── cert-operator.clusterserviceversion.yaml
    └── metadata
        └── annotations.yaml

I build the bundle like this:

`MY_BUNDLE_IMAGE=proxy-ng:443/quarkus/cert-op-bdl:v0.0.2; docker build -t $MY_BUNDLE_IMAGE -f build/bundle/cert-operator/bundle.Dockerfile build/bundle/cert-operator/; docker push $MY_BUNDLE_IMAGE`

This is my simple catalog file `cert-operator.yaml` which resides outside the build folder:

```
Schema: olm.semver
GenerateMajorChannels: true
GenerateMinorChannels: true
Stable:
  Bundles:
  - Image: "proxy-ng:443/quarkus/cert-op-bdl:v0.0.2"
```

and here's the content from cert-operator.clusterserviceversion.yaml:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cert-operator
spec:
  customresourcedefinitions: {}
  displayName: cert-operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          - certificatesigningrequests/finalizers
          verbs:
          - get
          - list
          - watch
          - patch
          - update
          - create
          - delete
        serviceAccountName: cert-operator
      deployments:
      - name: cert-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/version: 1.0-SNAPSHOT
              app.kubernetes.io/name: cert-operator
          template:
            metadata:
              annotations:
                app.quarkus.io/build-timestamp: 2023-08-13 - 14:34:43 +0000
              labels:
                app.kubernetes.io/managed-by: quarkus
                app.kubernetes.io/version: 1.0-SNAPSHOT
                app.kubernetes.io/name: cert-operator
              namespace: default
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: proxy-ng:443/quarkus/cert-operator:1.0-SNAPSHOT
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                name: cert-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                startupProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/started
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
              serviceAccountName: cert-operator
    strategy: deployment
  installModes:
  - supported: true
    type: AllNamespaces
#  version: 0.0.1
```

If I run the following command with opm (1.28) `opm alpha render-template semver -o yaml < cert-operator.yaml > catalog/catalog.yaml` it fails complaining:
`2023/08/13 16:48:37 semver "stdin": render: unable to post-process bundle info: bundle "cert-operator" has invalid version "": Version string empty`

If I uncomment the last last line in cert-operator.clusterserviceversion.yaml, including the Version and run 

`MY_BUNDLE_IMAGE=proxy-ng:443/quarkus/cert-op-bdl:v0.0.2; docker build -t $MY_BUNDLE_IMAGE -f build/bundle/cert-operator/bundle.Dockerfile build/bundle/cert-operator/; docker push $MY_BUNDLE_IMAGE` again, 

`opm alpha render-template semver -o yaml < cert-operator.yaml > catalog/catalog.yaml` will then work fine.

With respect to the documentation https://docs.openshift.com/container-platform/4.13/rest_api/operatorhub_apis/clusterserviceversion-operators-coreos-com-v1alpha1.html there is no requirement for the version. And even here https://olm.operatorframework.io/docs/concepts/crds/clusterserviceversion/ nothing requires the version.

So, either some docs need an update or opm enforces something it should not OR I am missing something and still have to learn a lot ;-)
