### ISSUE TITLE
opm alpha render-template command generates different olm.package.name

### ISSUE THREAD

**Issue by AjayJagan** [operator-framework/operator-registry#1682]
Hi Team,
I am currently using the following command

```
opm alpha render-template basic \
		--migrate-level=bundle-object-to-csv-metadata \
		-o yaml \
		catalog/fbc-basic-template.yaml > catalog/operator.yaml
```
Where the `fbc-basic-template.yaml` has something like this

```
schema: olm.template.basic
entries:
  - schema: olm.package
    name: opendatahub-operator
    defaultChannel: fast
  - schema: olm.channel
    package: opendatahub-operator
    name: fast
    entries: 
    - name: opendatahub-operator.v2.22.0-2
  - schema: olm.bundle
    image: quay.io/ajaganat/opendatahub-operator-bundle:v2.22.0-2
```
When I try to run the command to generate the catalog, I expect the `olm.package.name` to be something like `name: opendatahub-operator.v2.22.0-2` but what I get is `name: opendatahub-operator.v2.29.0`

but if I pass the image tag as `v2.22.0`(or any standard semver) it is able to populate the correct olm.package.name.

Can you please help me understand why is this happening.
