### ISSUE TITLE
Issue: UNIQUE constraint failed: operatorbundle.name, error loading package into db

### ISSUE THREAD

**Issue by mew2057** [operator-framework/operator-registry#211]
I've been trying to smoke test an update for my operator in OLM, but I keep hitting this issue  in the `origin-operator-registry` pod:

```
time="2020-03-10T14:26:23Z" level=warning msg="strict mode disabled" error="error loading manifests from appregistry: error loading operator manifests: [error adding operator bundle : UNIQUE constraint failed: operatorbundle.name, error loading package into db: ibm-spectrum-scale-csi-operator.v1.1.0 specifies replacement that couldn't be found]" port=50051 type=appregistry
```

If I'm reading this error correctly when attempting to specify the `spec.replaces` for my new bundle the pod can't find my old CSV version, but the version name matches 1:1.

```  YAML
# Old Package
--
channels:
  - currentCSV: ibm-spectrum-scale-csi-operator.v1.0.1
    name: stable
defaultChannel: stable
packageName: ibm-spectrum-scale-csi-operator

# New Package
---
channels:
  - currentCSV: ibm-spectrum-scale-csi-operator.v1.1.0
    name: stable
defaultChannel: stable
packageName: ibm-spectrum-scale-csi-operator

# CSV Replaces Field for v1.1.0
  maturity: alpha
  provider:
    name: IBM
  version: 1.1.0
  replaces: ibm-spectrum-scale-csi-operator.v1.0.1
```

I'm confused as to what I'm  doing wrong with the  replaces, because it looks identical to releases with upgrades in [Community Operators](https://github.com/operator-framework/community-operators).

## Environment
**k8s:** 1.16.3

```
# origin-operator-registry image version
Image ID:      docker-pullable://quay.io/openshift/origin-operator-registry@sha256:965297925da5b7395718592fe84292bc61530f892087fe53d22a779b10a21772
```

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
