### ISSUE TITLE
Is it possible add optional objects field in configmap registry server？

### ISSUE THREAD

**Issue by win5do** [operator-framework/operator-registry#452]
According to the docs, optional objects can be added to the bundle, I want add some Service yaml for webhook.

https://docs.okd.io/latest/operators/olm-packaging-format.html#olm-bundle-format-manifests_olm-packaging-format

Bundle image is very troublesome, I hope it can be done with configMap. But now only three fields are supported.

https://github.com/operator-framework/operator-registry/blob/cac3168e6cbbfb76bf4d385233a399af37df3872/pkg/sqlite/configmap.go#L20-L22

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: demo-configmap
spec:
  sourceType: configmap
  configMap: demo-configmap
  displayName: demo-operator
  publisher: xxx
```
