### ISSUE TITLE
`opm index add` is unable to handle non-default channel

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-registry#554]
Hi opm team,

`opm` tool is unable to add an operator which is older in non-default channel. Or, maybe `opm` doesn't support releasing older version if newer is present. So releasing `2.0.6` if `2.1.1` is present causes failure message. Can you please confirm which case it is?

`opm index add -u podman --bundles quay.io/operator_testing/infinispan:0bf45825 --tag quay.io/operator_testing/catalog:0bf45825 --mode replaces`

```
[quay.io/operator_testing/infinispan:0bf45825]" error="Invalid bundle infinispan-operator.v2.0.6, references nonexistent default channel 2.1.x"
```

```
channels:
- currentCSV: infinispan-operator.v2.0.4
  name: dev-preview
- currentCSV: infinispan-operator.v1.1.2
  name: stable
- currentCSV: infinispan-operator.v1.1.2
  name: 1.1.x
- currentCSV: infinispan-operator.v2.0.6
  name: 2.0.x
- currentCSV: infinispan-operator.v2.1.1
  name: 2.1.x
defaultChannel: 2.1.x
packageName: infinispan
```

source PR: https://github.com/operator-framework/community-operators/pull/2946
error log: https://github.com/operator-framework/community-operators/runs/1720472363?check_suite_focus=true#step:2:437
