### ISSUE TITLE
Last version of origin-registry operator complains with could not decode contents of file /registry/bundles.db into package: error converting YAML to JSON: yaml: control characters are not allowed" dir=/registry file=bundles.db load=package

### ISSUE THREAD

**Issue by qinqon** [operator-framework/operator-registry#70]
It wasn't an error before but after operator-registry merged https://github.com/operator-framework/operator-registry/commit/065e51f2d66d4f44d9c32c158c1738c2fa765a05 it's an error.

error:
```
time="2019-08-08T10:42:49Z" level=info msg="could not decode contents of file /registry/bundles.db into package: error converting YAML to JSON: yaml: control characters are not allowed" dir=/registry file=bundles.db load=package
D
```

Before commit merged:
https://travis-ci.com/kubevirt/cluster-network-addons-operator/builds/122417674#L1343

After commit merged:
https://travis-ci.com/kubevirt/cluster-network-addons-operator/builds/122546641#L1347

Is this really fatal ? 

We are exercising this with latest version of quay.io/openshift/origin-operator-registry

**Comment by njhale** [comment]
Sorry for the delay. This should not be fatal. Will open a PR with a fix soon.

**Comment by bandrade** [comment]
I've tested this PR using a synthetic catalog with the following structure to explicitly trigger the `replaces` + `skips` conflict detection introduced by this PR.

---

### 📦 Catalog Structure

All files were placed under a directory named `minimal-test`, and used `.yaml` extension to ensure `opm validate` would parse them.

#### `test.package.yaml`
```yaml
schema: olm.package
name: test-operator
defaultChannel: stable-v1
```

stable-v1.channel.yaml
```yaml
schema: olm.channel
name: stable-v1
package: test-operator
entries:
  - name: test-operator-v1.0.0
  - name: test-operator-v1.1.0
  - name: test-operator-v1.1.2
  - name: test-operator-v1.1.4
    replaces: test-operator-v1.0.0
    skips:
      - test-operator-v1.0.0
      - test-operator-v1.1.0
      - test-operator-v1.1.2
  - name: test-operator-v1.2.0
  - name: test-operator-v1.2.1
    replaces: test-operator-v1.1.4
    skips:
      - test-operator-v1.1.4     # <- conflict with replaces
      - test-operator-v1.2.0
  - name: test-operator-v1.3.0
    replaces: test-operator-v1.2.1
    skips:
      - test-operator-v1.2.1     # <- conflict with replaces
  - name: test-operator-v1.4.0
    replaces: test-operator-v1.3.0
    skips:
      - test-operator-v1.3.0     # <- conflict with replaces
```

test-operator-<version>.bundle.yaml (for each version)

Each file includes the required olm.package property, e.g.:
```
schema: olm.bundle
name: test-operator-v1.2.1
package: test-operator
image: quay.io/example/test-operator:v1.2.1
properties:
  - type: olm.package
    value:
      packageName: test-operator
      version: 1.2.1
````

opm validate completed without any errors.

I was expecting results like this
````
invalid package "test-operator", channel "stable-v1": entry "test-operator-v1.2.1" has identical replaces and skips: "test-operator-v1.1.4"
invalid package "test-operator", channel "stable-v1": entry "test-operator-v1.3.0" has identical replaces and skips: "test-operator-v1.2.1"
invalid package "test-operator", channel "stable-v1": entry "test-operator-v1.4.0" has identical replaces and skips: "test-operator-v1.3.0"
```
Could you validate if is there something wrong on my test? Thanks
