### ISSUE TITLE
skipRange does not seem to work as documented for file-based catalogs

### ISSUE THREAD

**Issue by amisevsk** [operator-framework/operator-registry#822]
### Description
The [documentation](https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/#skiprange) for file-based catalogs suggests using skipRange to configure e.g. one-hop upgrades from bugfixes to a new minor release:
```yaml
schema: olm.channel
package: myoperator
channel: stable
entries:
  - name: myoperator.v1.0.3
    skipRange: ">=1.0.0 <1.0.3"
```
However, attempting to do this in a catalog causes `opm validate` to fail with `multiple channel heads found in graph`.

The only way to resolve this is to add a `replaces` field for the previous channel head (i.e. `replaces myoperator.v1.0.2`). I haven't tested if skipRange works as expected in this case.

### Reproducing
The following catalog appears to be valid according to the documentation but fails validation:
```yaml
schema: olm.package
defaultChannel: alpha
name: test-operator
---
schema: olm.channel
package: test-operator
name: alpha
entries:
  - name: test-operator.v1.0.0
  - name: test-operator.v1.0.1
    replaces: test-operator.v1.0.0
  - name: test-operator.v1.0.2
    skipRange: ">=1.0.0 <1.0.2"
---
schema: olm.bundle
image: quay.io/test-image
name: test-operator.v1.0.0
package: test-operator
properties:
- type: olm.package
  value:
    packageName: test-operator
    version: 1.0.0
---
schema: olm.bundle
image: quay.io/test-image
name: test-operator.v1.0.1
package: test-operator
properties:
- type: olm.package
  value:
    packageName: test-operator
    version: 1.0.1
---
schema: olm.bundle
image: quay.io/test-image
name: test-operator.v1.0.2
package: test-operator
properties:
- type: olm.package
  value:
    packageName: test-operator
    version: 1.0.2
```
error is
```
FATA[0000] invalid index:
└── invalid package "test-operator":
    └── invalid channel "alpha":
        └── multiple channel heads found in graph: test-operator.v1.0.1, test-operator.v1.0.2 
```

**Comment by joelanford** [comment]
This is working as intended. OLM's resolver requires a single linear replaces chain per channel.

You have two options:
1. Add `replaces: test-operator.v1.0.1` to the `test-operator.v1.0.2` entry. Choose this option if you want 1.0.1 and 1.0.0 to be installable via a subscription's startingCSV.
2. Remove the entries for `test-operator.v1.0.1` and `test-operator.v1.0.0`. Choose this option if you only want 1.0.2 to be installable (but still upgradable from anything in the skipRange)

**Comment by amisevsk** [comment]
I'm not sure this issue should be closed -- while it may be intended functionality, the documentation still points users in a confusing direction:

> The entry specifying the `skipRange` will be presented as a direct (one hop) update to any version from that package within that range. The versions in this range **do not need to be in the catalog** in order for bundle addition to be successful.

(i.e. "but could be" -- nothing is mentioned about still requiring a linear replaces chain)

It would be useful if the documentation mentioned that `replaces` is still required with `skipRange` when there is more than one version. Compare this to the example used for the "Skips" section, which includes the replaces field even though the catalog does not contain `myoperator.v1.0.0`:
```yaml
  - name: myoperator.v1.0.3
    replaces: myoperator.v1.0.0
    skips:
      - myoperator.v1.0.1
      - myoperator.v1.0.2
```

Perhaps the "SkipRange" example should be
```yaml
  - name: myoperator.v1.0.3
    replaces: myoperator.v1.0.0
    skipRange: ">=1.0.0 <1.0.3"
```
to match.
