### ISSUE TITLE
opm: diff is not pruning empty channel when an include config is provided

### ISSUE THREAD

**Issue by jpower432** [operator-framework/operator-registry#883]
`opm alpha diff -i config.yaml` is producing empty channels when an include config is providers and no old refs are specified.

Config:

```
packages:
  - name: rhacs-operator
    channels:
    - name: latest
    versions:
    - '3.67.0'
```

Results:
```
{
    "schema": "olm.channel",
    "name": "rhacs-3.66",
    "package": "rhacs-operator",
    "entries": []
}
opm validate of the catalog show this:

$ opm validate catalogs/
FATA[0000] invalid index:
└── invalid package "rhacs-operator":
    ├── invalid channel "rhacs-3.62":
    │   └── channel must contain at least one bundle
    ├── invalid channel "rhacs-3.64":
    │   └── channel must contain at least one bundle
    ├── invalid channel "rhacs-3.65":
    │   └── channel must contain at least one bundle
    └── invalid channel "rhacs-3.66":
        └── channel must contain at least one bundle
```
