### ISSUE TITLE
FBC: Add properties to olm.package and olm.channel

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#895]
Problem:  There is no simple way to add third-party metadata to File Based Catalogs.  The options include:
1.  Adding labels to the built catalog image.
2. Adding files to the catalog image
3. Adding custom fields to the catalog yaml

The problem with all three of these approaches is that none of the tooling preserves this additional metadata since it is not part of the Go blob schema for these objects.

**Solution:**
To solve this, I'd like to see adding Properties to the `olm.package` and `olm.channel` blobs, just like the properties format for the `olm.bundle` blob.

Example:
```yaml
schema: olm.package
name: foo
defaultChannel: v1
properties:
- type: ibm.epoch
   value: 20220111.223045.00000
- type: ibm.version
   value: 4
```

Slack conversation history:
https://kubernetes.slack.com/archives/C0181L6JYQ2/p1640821737179600
