### ISSUE TITLE
Clearly promote properties.yaml and start deprecation of dependencies.yaml

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#912]
In early 2021, Bundles were enhanced to support describing arbitrary properties in bundles (e.g. `properties.yaml`).  These properties include the data in `dependencies.yaml`.  `opm registry|index add` in fact translates both the properties and dependencies to the `properties` table, which is used by the `grpc` interface.

A lot of the internal documentation and EP's are starting to favor describing user scenarios via properties instead of dependencies.yaml.  This is likely because File Based Catalog `olm.bundle` objects also expose dependencies as properties and it's easier to use one language vs. describing it both ways.

As discussed at the OLM dev call on Jan 27, 2022, there is a bit of hesitation to officially deprecate `dependencies.yaml `yet.  Although the usefulness of it will decrease over time as properties.yaml becomes more mainstream.

So the ask here is:
Clearly document how to describe dependencies in the properties.yaml, the versions of OPM are required (1.17.4 and OpenShift 4.9) to exploit it.  Provide examples and how to translate, and also include information on how conflicts are handled (if at all).

Example:
dependencies.yaml:
```yaml
dependencies:
  - type: olm.package
    value:
      packageName: testoperatorc
      version: ">=3.0.0"
```

properties.yaml (with some other properties in it as well):
```yaml
properties:
  - type: olm.gvk
    value:
      group: sample.ibm.com
      kind: TestOperatorA
      version: v1
  - type: olm.package
    value:
      packageName: testoperatora
      version: 1.0.1
  - type: olm.package.required
    value:
      packageName: testoperatorc
      versionRange: '>=3.0.0'
```
