### ISSUE TITLE
Document the setup of a ConfigMap Operator Registry

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-registry#93]
I'm looking through the code to figure out how to setup a ConfigMap Operator Registry.  I figured I'd drop what I found which seems like it would be good to document here. I'd be thankful for any corrections.

Arguments to configmap-server
```
--debug Default: false, "enable debug logging"
--kubeconfig -k Required (or use ENV?) "absolute path to kubeconfig file"
--database -d Default: bundles.db "name of db to output"
--configMapName -c Required "name of a configmap"
--configMapNamespace -n Required "namespace of a configmap"
--port -p Default: 50051 "port number to serve on"
```
ENVs for configmap-server:
```
KUBERNETES_SERVICE_HOST
KUBERNETES_SERVICE_PORT
```

The config map needs to be in the following form
```
apiVersion: v1
kind: ConfigMap
metadata: 
  name: operator-registry
  namespace: default
data:
  customResourceDefinitions: |-
    Paste Your CRDs Here
  clusterServiceVersions: |-
    Paste Your CSVs Here
  packages: |-
    Paste Your Package YAML here
```

**Relevant Documents:** 
https://github.com/operator-framework/operator-registry/blob/master/configmap-registry.Dockerfile
https://github.com/operator-framework/operator-registry/blob/master/configmap.example.yaml
https://github.com/operator-framework/operator-registry/tree/master/cmd/configmap-server
